import { useEffect, useState, useCallback } from "react";
import { Link } from "react-router-dom";
import { getQuotations, getQuotationStats, getErrorMessage } from "../../services/manager.service";
import ApprovalStatusBadge from "../../components/manager/ApprovalStatusBadge";
import RiskBadge from "../../components/manager/RiskBadge";
import { LoadingState, ErrorState, EmptyState } from "../../components/manager/EmptyState";

const ManagerQuotations = () => {
	const [quotations, setQuotations] = useState([]);
	const [stats, setStats] = useState(null);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState("");
	const [statusFilter, setStatusFilter] = useState("ALL");
	const [riskFilter, setRiskFilter] = useState("ALL");
	const [searchQuery, setSearchQuery] = useState("");

	const loadData = useCallback(() => {
		setLoading(true);
		setError("");
		const params = {};
		if (statusFilter !== "ALL") params.status = statusFilter;
		if (riskFilter !== "ALL") params.riskLevel = riskFilter;

		Promise.allSettled([
			getQuotations(params),
			getQuotationStats(),
		])
			.then(([listRes, statsRes]) => {
				if (listRes.status === "fulfilled") {
					const resData = listRes.value.data;
					setQuotations(Array.isArray(resData) ? resData : resData?.quotations || []);
				} else {
					setError(getErrorMessage(listRes.reason));
				}

				if (statsRes.status === "fulfilled") {
					setStats(statsRes.value.data);
				}
				setLoading(false);
			})
			.catch((err) => {
				setError(getErrorMessage(err));
				setLoading(false);
			});
	}, [statusFilter, riskFilter]);

	useEffect(() => {
		let active = true;
		const params = {};
		if (statusFilter !== "ALL") params.status = statusFilter;
		if (riskFilter !== "ALL") params.riskLevel = riskFilter;

		Promise.allSettled([
			getQuotations(params),
			getQuotationStats(),
		])
			.then(([listRes, statsRes]) => {
				if (!active) return;
				if (listRes.status === "fulfilled") {
					const resData = listRes.value.data;
					setQuotations(Array.isArray(resData) ? resData : resData?.quotations || []);
				} else {
					setError(getErrorMessage(listRes.reason));
				}

				if (statsRes.status === "fulfilled") {
					setStats(statsRes.value.data);
				}
				setLoading(false);
			})
			.catch((err) => {
				if (active) {
					setError(getErrorMessage(err));
					setLoading(false);
				}
			});

		return () => {
			active = false;
		};
	}, [statusFilter, riskFilter]);

	const filteredList = quotations.filter((q) => {
		if (!searchQuery.trim()) return true;
		const query = searchQuery.toLowerCase();
		const qNum = (q.quotationNumber || "").toLowerCase();
		const cust = (q.customer?.name || q.customerName || "").toLowerCase();
		const rep = (q.salesRep?.name || q.salesRepName || "").toLowerCase();
		return qNum.includes(query) || cust.includes(query) || rep.includes(query);
	});

	return (
		<div>
			<div className="page-header">
				<div>
					<h1>Team Quotations</h1>
					<p className="page-description">
						Governance and review of all quotations generated by your sales team.
					</p>
				</div>
			</div>

			{/* Stats Bar if available */}
			{stats ? (
				<div className="metric-grid" style={{ marginBottom: "20px" }}>
					<div className="metric-card">
						<span>Total Team Quotes</span>
						<strong>{stats.total ?? quotations.length}</strong>
					</div>
					<div className="metric-card">
						<span>Pending Approval</span>
						<strong>{stats.pendingApproval ?? 0}</strong>
					</div>
					<div className="metric-card">
						<span>Approved Quotes</span>
						<strong>{stats.approved ?? 0}</strong>
					</div>
					<div className="metric-card">
						<span>Total Quoted Value</span>
						<strong>${(stats.totalValue ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</strong>
					</div>
				</div>
			) : null}

			{/* Toolbar Filters */}
			<div className="toolbar">
				<input
					type="text"
					className="search-input"
					placeholder="Search by quote #, customer, or sales rep..."
					value={searchQuery}
					onChange={(e) => setSearchQuery(e.target.value)}
				/>

				<select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
					<option value="ALL">All Statuses</option>
					<option value="DRAFT">Draft</option>
					<option value="PENDING_APPROVAL">Pending Approval</option>
					<option value="APPROVED">Approved</option>
					<option value="REJECTED">Rejected</option>
				</select>

				<select value={riskFilter} onChange={(e) => setRiskFilter(e.target.value)}>
					<option value="ALL">All Risk Levels</option>
					<option value="LOW">Low Risk</option>
					<option value="MEDIUM">Medium Risk</option>
					<option value="HIGH">High Risk</option>
				</select>

				<span className="toolbar-note">
					Showing {filteredList.length} team quotations
				</span>
			</div>

			{loading ? (
				<LoadingState message="Loading team quotations..." />
			) : error ? (
				<ErrorState message={error} onRetry={loadData} />
			) : filteredList.length === 0 ? (
				<EmptyState
					title="No quotations found"
					description="No team quotations match your active filter criteria."
				/>
			) : (
				<div className="table-panel">
					<div className="table-head" style={{ gridTemplateColumns: "1.2fr 1.3fr 1.1fr 1fr 0.9fr 0.9fr 1fr 0.7fr" }}>
						<div>Quotation #</div>
						<div>Customer</div>
						<div>Sales Rep</div>
						<div>Amount</div>
						<div>Margin</div>
						<div>Risk Level</div>
						<div>Status</div>
						<div>Action</div>
					</div>

					{filteredList.map((q) => {
						const id = q._id || q.id;
						const qNum = q.quotationNumber || "—";
						const customerName = q.customer?.name || q.customerName || "Customer";
						const repName = q.salesRep?.name || q.salesRepName || "Sales Rep";
						const amount = q.grandTotal ?? q.subtotal ?? 0;
						const margin = q.margin ?? q.marginPercent ?? 0;
						const riskLevel = q.riskLevel || "LOW";
						const riskScore = q.riskScore ?? 0;

						return (
							<div
								key={id}
								className="table-row"
								style={{ gridTemplateColumns: "1.2fr 1.3fr 1.1fr 1fr 0.9fr 0.9fr 1fr 0.7fr" }}
							>
								<div>
									<strong>{qNum}</strong>
									<small>{q.createdAt ? new Date(q.createdAt).toLocaleDateString() : ""}</small>
								</div>
								<div>
									<strong>{customerName}</strong>
									<small>{q.customer?.tier || "Standard"}</small>
								</div>
								<div>
									<strong>{repName}</strong>
								</div>
								<div>
									<strong>${amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</strong>
								</div>
								<div>
									<strong>{typeof margin === "number" ? `${margin.toFixed(1)}%` : margin}</strong>
								</div>
								<div>
									<RiskBadge level={riskLevel} score={riskScore} />
								</div>
								<div>
									<ApprovalStatusBadge status={q.status} />
								</div>
								<div>
									<Link
										to={`/sales-manager/quotations/${id}`}
										className="button button-secondary"
										style={{ padding: "5px 10px", fontSize: "11px" }}
									>
										Inspect
									</Link>
								</div>
							</div>
						);
					})}
				</div>
			)}
		</div>
	);
};

export default ManagerQuotations;
